# Generated by Django 3.2.6 on 2021-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=254)),
                ('curso', models.IntegerField(choices=[(0, '2022-1')], default=0)),
                ('is_student', models.BooleanField(default=True)),
                ('matricula', models.CharField(default='', max_length=12)),
                ('carrera', models.IntegerField(choices=[(1, 'Aplicadas'), (2, 'Matemáticas'), (3, 'Física'), (4, 'Actuaría')], default=0)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
