# Generated by Django 3.2.6 on 2021-09-23 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenResuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_id', models.TextField(blank=True, default='', max_length=100)),
                ('curso', models.TextField(blank=True, default='', max_length=100)),
                ('numero_cuenta', models.TextField(blank=True, default='', max_length=100)),
                ('tema', models.TextField(blank=True, default='', max_length=100)),
                ('tiempo', models.TextField(blank=True, default='', max_length=100)),
                ('calificacion', models.TextField(blank=True, default='', max_length=10)),
                ('pregunta1', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta1_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta2', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta2_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta3', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta3_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta4', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta4_calif', models.TextField(blank=True, default='', max_length=10000)),
                ('pregunta5', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_correcta', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_alumno', models.TextField(blank=True, default='', max_length=10000)),
                ('respuesta5_calif', models.TextField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.IntegerField(choices=[(0, '2022-1')], default=0)),
                ('tema', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('pregunta1', models.IntegerField(choices=[(0, '¿Cuál es la notación en python de $sqrt(random)$?'), (1, '¿Cuál es la notación en python de $random**random$?'), (2, '¿Cuál es la notación en python de $random*random$?'), (3, '¿Qué lenguaje de programación aprenderas en el curso'), (4, '¿Cual es el nombre del profesor que imparte este curso?')], default=0)),
                ('pregunta2', models.IntegerField(choices=[(0, '¿Cuál es la notación en python de $sqrt(random)$?'), (1, '¿Cuál es la notación en python de $random**random$?'), (2, '¿Cuál es la notación en python de $random*random$?'), (3, '¿Qué lenguaje de programación aprenderas en el curso'), (4, '¿Cual es el nombre del profesor que imparte este curso?')], default=0)),
                ('pregunta3', models.IntegerField(choices=[(0, '¿Cuál es la notación en python de $sqrt(random)$?'), (1, '¿Cuál es la notación en python de $random**random$?'), (2, '¿Cuál es la notación en python de $random*random$?'), (3, '¿Qué lenguaje de programación aprenderas en el curso'), (4, '¿Cual es el nombre del profesor que imparte este curso?')], default=0)),
                ('pregunta4', models.IntegerField(choices=[(0, '¿Cuál es la notación en python de $sqrt(random)$?'), (1, '¿Cuál es la notación en python de $random**random$?'), (2, '¿Cuál es la notación en python de $random*random$?'), (3, '¿Qué lenguaje de programación aprenderas en el curso'), (4, '¿Cual es el nombre del profesor que imparte este curso?')], default=0)),
                ('pregunta5', models.IntegerField(choices=[(0, '¿Cuál es la notación en python de $sqrt(random)$?'), (1, '¿Cuál es la notación en python de $random**random$?'), (2, '¿Cuál es la notación en python de $random*random$?'), (3, '¿Qué lenguaje de programación aprenderas en el curso'), (4, '¿Cual es el nombre del profesor que imparte este curso?')], default=0)),
                ('activo', models.BooleanField(default=True)),
                ('is_test', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
